### ISSUE TITLE
View user dashboard

### ISSUE THREAD

**Issue by dantetemplar** [one-zero-eight/InNoHassle-Website#10]
- [x] API-connected part:
- [x] Display user info (email, name, status) on the website
- [x] View of favorites and groups

Example of API response /users/me:
```{
  "id": 282,
  "email": "r.belkov@innopolis.university",
  "name": "Ruslan Belkov",
  "status": "Student",
  "groups_association": [
    {
      "user_id": 282,
      "group": {
        "id": 2,
        "path": "electives/BS-Tech/PP.ics",
        "name": "Programming in Python",
        "type": "elective"
      },
      "hidden": false
    },
    {
      "user_id": 282,
      "group": {
        "id": 5,
        "path": "electives/BS-MS-Hum/CL.ics",
        "name": "Career and Leadership",
        "type": "elective"
      },
      "hidden": false
    },
    {
      "user_id": 282,
      "group": {
        "id": 33,
        "path": "core-courses/BS-Year-1/B22-DSAI-04.ics",
        "name": "B22-DSAI-04",
        "type": "core courses"
      },
      "hidden": true
    }
  ],
  "favorites_association": []
}
```
