### ISSUE TITLE
Choose interface theme

### ISSUE THREAD

**Issue by dantetemplar** [one-zero-eight/InNoHassle-Website#3]
- [x] #28 
- [x] Add light theme support for components
- [x] Add light theme support for calendar
- [x] Create theme switch

# User Story

**As a** user

**I want to** choose between light and dark theme

**So that** I can use the service with comfort

**Comment by danmaninc** [comment]
**Requires #28** to establish constant color palettes for each theme.

**Comment by ArtemSBulgakov** [comment]
Please, add icons to display dark and light theme on button

**Comment by danmaninc** [comment]
> Please, add icons to display dark and light theme on button

Added by the https://github.com/one-zero-eight/InNoHassle-Website/commit/301751bff4e6c08b349047a0468a9d3a9989f345
