### ISSUE TITLE
Add tags support

### ISSUE THREAD

**Issue by danmaninc** [one-zero-eight/InNoHassle-Website#48]
Support the EventGroup tags developed by https://github.com/one-zero-eight/InNoHassle-Events/issues/30.
- [ ] Create component of the tag with «Remove» button as in Figma
- [ ] Add category tags on corresponding pages
- [ ] Add possibility to choose tags manually
